config/routes.rb
Rails.application.routes.draw do
  resources :remuneracoes
  resources :turnos
  resources :funcionarios

  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/remuneracao.rb
class Remuneracao < ApplicationRecord
  belongs_to :funcionario
end

app/models/turno.rb
class Turno < ApplicationRecord
  belongs_to :funcionario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      @qtd_funcionarios = Funcionario.count
      @qtd_turnos = Turno.count
      @qtd_remuneracoes = Remuneracao.count
    end
  end
  

app/controllers/remuneracoes_controller.rb
class RemuneracoesController < ApplicationController
  before_action :set_remuneracao, only: [:show, :edit, :update, :destroy]

  # GET /remuneracoes
  # GET /remuneracoes.json
  def index
    @remuneracoes = Remuneracao.all
  end

  # GET /remuneracoes/1
  # GET /remuneracoes/1.json
  def show
  end

  # GET /remuneracoes/new
  def new
    @remuneracao = Remuneracao.new
  end

  # GET /remuneracoes/1/edit
  def edit
  end

  # POST /remuneracoes
  # POST /remuneracoes.json
  def create
    @remuneracao = Remuneracao.new(remuneracao_params)

    respond_to do |format|
      if @remuneracao.save
        format.html { redirect_to @remuneracao, notice: 'Remuneracao was successfully created.' }
        format.json { render :show, status: :created, location: @remuneracao }
      else
        format.html { render :new }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remuneracoes/1
  # PATCH/PUT /remuneracoes/1.json
  def update
    respond_to do |format|
      if @remuneracao.update(remuneracao_params)
        format.html { redirect_to @remuneracao, notice: 'Remuneracao was successfully updated.' }
        format.json { render :show, status: :ok, location: @remuneracao }
      else
        format.html { render :edit }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remuneracoes/1
  # DELETE /remuneracoes/1.json
  def destroy
    @remuneracao.destroy
    respond_to do |format|
      format.html { redirect_to remuneracoes_url, notice: 'Remuneracao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remuneracao
      @remuneracao = Remuneracao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def remuneracao_params
      params.require(:remuneracao).permit(:funcionario_id, :salario)
    end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turno_params
      params.require(:turno).permit(:funcionario_id, :entrada, :saida)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/remuneracoes_helper.rb
module RemuneracoesHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario, local: true) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2>Confira os erros abaixo:</h2>

      <ul>
        <% funcionario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando Funcionario</h1>

  <%= render 'form', funcionario: @funcionario %>

  <%= link_to 'Mostrar', @funcionario %> |
  <%= link_to 'Voltar', funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Funcionarios</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Dias trabalhados</th>
        <th>Valor a receber</th>
        <th>Histórico do turno</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.dias_trabalhados %></td>
        <td>R$ <%= funcionario.valor_receber.round(2) %></td>
        <td><%= link_to 'Turnos', "#{turnos_path}?funcionario_id=#{funcionario.id}", class: "btn btn-primary" %></td>
        <td><%= link_to 'Mostrar', funcionario, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario), class: "btn btn-warning" %></td>
        <td><%= link_to 'Apagar', funcionario, method: :delete, data: { confirm: 'Você tem certeza ??' }, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_funcionario_path, class: "btn btn-primary" %>
</div>

app/views/funcionarios/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', funcionario: @funcionario %>

  <%= link_to 'Voltar', funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <%= @funcionario.nome %>
  </p>

  <%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
  <%= link_to 'Voltar', funcionarios_path %>
</div>

app/views/home/index.html.erb
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-4 col-8">
        <!-- small box -->
        <div class="small-box bg-info">
          <div class="inner">
            <h3><%= @qtd_funcionarios %></h3>

            <p>Funcionários</p>
          </div>
          <div class="icon">
            <i class="ion ion-bag"></i>
          </div>
          <a href="/funcionarios" class="small-box-footer">Ver funcionários <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-4 col-8">
        <!-- small box -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3><%= @qtd_turnos %></h3>

            <p>Turnos</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="/turnos" class="small-box-footer">Ver turnos <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-4 col-8">
        <!-- small box -->
        <div class="small-box bg-warning">
          <div class="inner">
            <h3><%= @qtd_remuneracoes %></h3>

            <p>Remunerações</p>
          </div>
          <div class="icon">
            <i class="ion ion-person-add"></i>
          </div>
          <a href="/remuneracoes" class="small-box-footer">Ver remunerações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Gestão de Ponto</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Gestão de ponto</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="/funcionarios" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Funcionários
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/turnos" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Turnos
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/remuneracoes" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Remunerações
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <%= yield %>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2020-2021 <a href="lfernandotc@hotmail.com/">Luís Fernando C. Trindade</a>.</strong>
    Todos os diretos para este software são livres, fique a vontade em utilizar.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 0.0.1
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
</body>
</html>

app/views/remuneracoes/_form.html.erb
<%= form_with(model: remuneracao) do |form| %>
  <% if remuneracao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remuneracao.errors.count, "error") %> prohibited this remuneracao from being saved:</h2>

      <ul>
        <% remuneracao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.text_field :funcionario_id %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/remuneracoes/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando</h1>

  <%= render 'form', remuneracao: @remuneracao %>

  <%= link_to 'Mostrar', @remuneracao %> |
  <%= link_to 'Voltar', remuneracoes_path %>
</div>

app/views/remuneracoes/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Remunerações</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Funcionario</th>
        <th>Salario</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @remuneracoes.each do |remuneracao| %>
      <tr>
        <td><%= remuneracao.funcionario.nome %></td>
        <td><%= remuneracao.salario %></td>
        <td><%= link_to 'Mostrar', remuneracao %></td>
        <td><%= link_to 'Editar', edit_remuneracao_path(remuneracao) %></td>
        <td><%= link_to 'Apagar', remuneracao, method: :delete, data: { confirm: 'Você tem certeza ??' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_remuneracao_path, class: "btn btn-primary" %>
</div>

app/views/remuneracoes/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', remuneracao: @remuneracao %>

  <%= link_to 'Voltar', remuneracoes_path %>
</div>

app/views/remuneracoes/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Funcionario:</strong>
    <%= @remuneracao.funcionario_id %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= @remuneracao.salario %>
  </p>

  <%= link_to 'Editar', edit_remuneracao_path(@remuneracao) %> |
  <%= link_to 'Voltar', remuneracoes_path %>
</div>

app/views/turnos/_form.html.erb
<%= form_with(model: turno, local: true) do |form| %>
  <% if turno.errors.any? %>
    <div id="error_explanation">
      <h2>Confira os erros abaixo:</h2>

      <ul>
        <% turno.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.select(:funcionario_id, Funcionario.all.collect {|f| [f.nome, f.id]}) %>
  </div>

  <div class="field">
    <%= form.label :entrada %>
    <%= form.datetime_field :entrada %>
  </div>

  <div class="field">
    <%= form.label :saida %>
    <%= form.datetime_field :saida %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando Turno</h1>

  <%= render 'form', turno: @turno %>

  <%= link_to 'Mostrar', @turno %> |
  <%= link_to 'Voltar', turnos_path %>
</div>

app/views/turnos/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Turnos</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Funcionario</th>
        <th>Entrada</th>
        <th>Saida</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.funcionario.nome %></td>
        <td><%= turno.entrada.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= turno.saida.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to 'Mostrar', turno %></td>
        <td><%= link_to 'Editar', edit_turno_path(turno) %></td>
        <td><%= link_to 'Apagar', turno, method: :delete, data: { confirm: 'Você tem certeza ??' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_turno_path, class: "btn btn-primary" %>
</div>

app/views/turnos/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', turno: @turno %>

  <%= link_to 'Voltar', turnos_path %>
</div>

app/views/turnos/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Funcionario:</strong>
    <%= @turno.funcionario_id %>
  </p>

  <p>
    <strong>Entrada:</strong>
    <%= @turno.entrada.strftime("%d/%m/%Y %H:%M") %>
  </p>

  <p>
    <strong>Saida:</strong>
    <%= @turno.saida.strftime("%d/%m/%Y %H:%M") %>
  </p>

  <%= link_to 'Editar', edit_turno_path(@turno) %> |
  <%= link_to 'Voltar', turnos_path %>
</div>